name: Release

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: |
        cd server
      - run: docker build -t 19127098/server:lastest .
      - run: docker login -u ${{secrets.DOCKER_HUB_USERNAME}} -p ${{secrets.DOCKER_HUB_PASSWORD}}
      - run: docker push 19127098/server:lastest

  cd:
    runs-on: self-hosted
    needs: deploy
    steps:
      - uses: actions/checkout@v3
      - run: sudo docker pull 19127098/server:lastest
      - run: sudo docker rm -f server
      - run: sudo docker run -d -p 80:80 --name server 19127098/server